<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
	<!ELEMENT agenda (contacto+)>
		<!ELEMENT contacto (nombre, apellidos, telefono)>
			<!ELEMENT nombre (#PCDATA)>
			<!ELEMENT apellidos (#PCDATA)>
			<!ELEMENT telefono (#PCDATA)>
]>

<agenda>
	<contacto>
		<nombre>Juan Carlos</nombre>
		<apellidos>Sanz Péres</apellidos>
		<telefono>622 123 456</telefono>
	</contacto>

	<contacto>
		<nombre>Ana</nombre>
		<apellidos>Pérez Sanz</apellidos>
		<telefono>633 123 456</telefono>
	</contacto>
</agenda>